- .gitattributes
- .gitignore
- README.md
This PR adds an initial README, `.gitignore`, and `.gitattributes`.
> add README and `.gitignore`

- README.md
This PR makes the README more clear about the fact that the Kubeflow Notebooks codebase currently lives on `kubeflow/kubeflow`.
> Update README with warning about migration

- OWNERS
Currently the owners file lists many people who are not maintainers.
This is a problem because all PRs are being assigned to people who are not related to the Notebooks development and slowing down the time to get a review.
__NOTE:__ This PR only updates the `notebooks-v2` branch, but we should make one for `main` also.
> chore: clean up OWNERS file (avoid non-maintainers)

- workspaces/controller/api/v1beta1/workspace_types.go
- workspaces/controller/api/v1beta1/workspacekind_types.go
- workspaces/controller/api/v1beta1/zz_generated.deepcopy.go
- workspaces/controller/config/crd/bases/kubeflow.org_workspacekinds.yaml
- workspaces/controller/config/crd/bases/kubeflow.org_workspaces.yaml
- workspaces/controller/internal/controller/workspace_controller_test.go
- workspaces/controller/internal/controller/workspacekind_controller_test.go
This PR makes the following changes to the workspace controller: 
- Uses the correct type for `spec.podTemplate.options.podConfig.values[].spec.nodeSelector`
- Ensures that the `spec` of `podConfig` and `imageConfig` values does not change
- Updates a few types to use the `+listType:="map"` because they should not support multiple elements with the same key:
- `spec.podTemplate.volumes.data[]` (keyed on `name`)
- `spec.podTemplate.extraEnv[]` (keyed on `name`)
I have also added tests for some of the more complicated `+kubebuilder:validation:XValidation` / `x-kubernetes-validations` we are doing, so we dont have to worry about regressions in the future.
> fix(ws): use correct `nodeSelector` type and add CRD validation tests

- workspaces/frontend/package-lock.json
- workspaces/frontend/package.json
- workspaces/frontend/src/index.tsx
Closes #10 
react-axe: help to fix and identify accessibility issues. The project was moved to another org so we will need to add them back later.
react-docgen-typescript-loader: it's not necessary. Leftover from the seed project
```shell
➜  frontend git:(main) ✗ npm install                                                                                                                  (kind-kubebuilder-cluster/default)
up to date, audited 1199 packages in 720ms
210 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
➜  frontend git:(main) ✗ npm audit                                                                                                                    (kind-kubebuilder-cluster/default)
found 0 vulnerabilities
```
> chore(ws): remove unused libraries `react-axe` and `react-docgen-typescript-loader`

- workspaces/controller/Makefile
This PR enhances the safety of running `make test-e2e` by implementing a confirmation prompt.
The `make test-e2e` command executes tests on the current Kubernetes cluster. This can potentially disrupt a production environment, as the tests include cleanup operations such as deleting cert-manager after completion.
1. Added a confirmation prompt before test execution:
- Displays the current Kubernetes cluster context
- Asks for user confirmation to proceed
2. Implemented a bypass option for CI/CD pipelines:
- Set environment variable `KUBEFLOW_TEST_PROMPT=FALSE` to skip the prompt
- The variable is case-insensitive (e.g., "FALSE", "false", or "False" are all valid)
3. User confirmation:
- Accepts "yes" or "y" (case-insensitive) to proceed with the tests
- Any other input will abort the …
> test(ws): add safety prompt for E2E test execution

- .github/workflows/controller-tests.yaml
- .github/workflows/workspaces-controller_unit-tests.yaml
This is something that works differently in new Kubebuilder, compared to what's in kubeflow/kubeflow notebook controller.
Previously, what they called e2e tests was running in envtest, but currently they expect to run in externally-provided kind. So, let's run this on CI as well, so we don't have dead code.
> ci(ws): run `make test-e2e` on GitHub Actions

- workspaces/controller/internal/controller/workspace_controller.go
- workspaces/controller/internal/controller/workspace_controller_test.go
This PR populates the `status.pauseTime` on the Workspace:
- Set `status.pauseTime` to current Unix epoch when paused.
- Reset `status.pauseTime` to 0 when unpaused.
> feat(ws): set `status.pauseTime` on workspace

- workspaces/backend/.golangci.yml
- workspaces/backend/README.md
- workspaces/backend/api/app.go
- workspaces/backend/api/errors.go
- workspaces/backend/api/healthcheck__handler_test.go
- workspaces/backend/api/healthcheck_handler.go
- workspaces/backend/api/helpers.go
- workspaces/backend/api/workspacekinds_handler.go
- workspaces/backend/api/workspaces_handler.go
- workspaces/backend/api/workspaces_handler_test.go
- workspaces/backend/api/workspaceskind_handler_test.go
- workspaces/backend/internal/models/workspacekinds.go
- workspaces/backend/internal/models/workspaces.go
- workspaces/backend/internal/repositories/repositories.go
- workspaces/backend/internal/repositories/workspacekinds.go
- workspaces/backend/internal/repositories/workspaces.go
- workspaces/backend/internal/server/server.go
This PR builds on top of https://github.com/kubeflow/notebooks/pull/61 and https://github.com/kubeflow/notebooks/pull/65:
- closes https://github.com/kubeflow/notebooks/issues/51
- closes https://github.com/kubeflow/notebooks/pull/61
- closes https://github.com/kubeflow/notebooks/pull/65
In this PR:
- Created handlers and repositories for get workspacekinds.
There is still more to do for https://github.com/kubeflow/notebooks/issues/49
> feat(ws): add CRUD operations to backend

- .github/workflows/controller-tests.yaml
- workspaces/controller/Makefile
- workspaces/controller/test/e2e/e2e_suite_test.go
- workspaces/controller/test/e2e/e2e_test.go
- workspaces/controller/test/utils/utils.go
This PR introduces the following changes:
- Removes the prompt for end-to-end (E2E) test execution.
- Adds checks to verify if the CertManager and Prometheus operators are already installed. This prevents reinstallation and avoids unnecessary deletion.
- Added support for skipping CertManager installation with the environment variable `CERT_MANAGER_INSTALL_SKIP`.
- Added support for skipping Prometheus installation with the environment variable `PROMETHEUS_INSTALL_SKIP`.
- Enhances the E2E test setup and cleanup.
These changes follow [discussions](https://kubernetes.slack.com/archives/CAR30FCJZ/p1724837864980059) with the Kubebuilder maintainer, who has already merged similar updates into Kubebuilder in this [PR](https://github.com/kubernetes-sigs/kubebuilder/pull/4106/files).
- …
> test(ws): enhance e2e test setup and cleanup

- .github/workflows/semantic-prs.yaml
This PR introduces a new GitHub Actions workflow to enforce semantic pull request titles for better clarity and consistency in the development process.
NOTE: this is the same as https://github.com/kubeflow/notebooks/pull/14, but for the `main` branch.
> ci: add action to enforce semantic PR titles

- workspaces/frontend/src/__mocks__/mockNamespaces.ts
- workspaces/frontend/src/__tests__/cypress/cypress/tests/e2e/NamespaceSelector.cy.ts
- workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
- workspaces/frontend/src/app/App.tsx
- workspaces/frontend/src/app/NavSidebar.tsx
- workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
- workspaces/frontend/src/app/context/NotebookContext.tsx
- workspaces/frontend/src/app/hooks/useMount.tsx
- workspaces/frontend/src/app/types.ts
- workspaces/frontend/src/shared/api/__tests__/notebookService.spec.ts
- workspaces/frontend/src/shared/api/notebookService.ts
- workspaces/frontend/src/shared/components/NamespaceSelector.tsx
> feat(ws): add namespace dropdown to UI

- workspaces/frontend/src/app/pages/Workspaces/DataVolumesList.tsx
- workspaces/frontend/src/app/pages/Workspaces/ExpandedWorkspaceRow.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/shared/types.ts
Fixes: #149
added popup with the worspace data vol info, that will show when hovering on the data vol column field.
please inform me if anything needs to be changes in matter of functionality or styling.
added a picture of the change:
> feat(ws): Add popup to Workspace data vol column in workspaces table

- workspaces/frontend/src/app/App.tsx
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsActions.tsx
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsOverview.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/shared/types.ts
Closes https://github.com/kubeflow/notebooks/issues/156 .
This PR implements the initial layout, with mocked data, for the Workspace details drawer:
Follow up issues to complete the Workspace details task:
* https://github.com/kubeflow/notebooks/issues/170
* https://github.com/kubeflow/notebooks/issues/171
* https://github.com/kubeflow/notebooks/issues/172
* https://github.com/kubeflow/notebooks/issues/173
> feat(ws): Notebooks 2.0 // Frontend // Workspaces details // Live mockup

- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsOverview.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/shared/style/MUI-theme.scss
Adds MUI support to Notebooks 2.0 UI. Applies theming to Workspace details drawer to align with MUI theming and KF Central UI.
Before:
After:
MUI [Responsive Drawer](https://mui.com/material-ui/react-drawer/#responsive-drawer):
KF Central UI (Aligns with list styling in "Overview" tab):
> feat(ws): Notebooks 2.0 // Frontend // Workspace details // Applies MUI Theming 

- workspaces/backend/api/workspaces_handler_test.go
- workspaces/backend/internal/models/workspaces.go
- workspaces/backend/internal/repositories/workspaces.go
This PR addresses [issue #127](https://github.com/kubeflow/notebooks/issues/127) by refactoring the workspace model and adjusting the JSON payload structure to align with the updated API requirements.
- **Workspace Model Updates**:
- Introduced new fields: `WorkspaceKind`, `PodTemplate`, `Activity`, and `Volumes`.
- Updated nested models (`PodMetadata`, `ImageConfig`, `PodConfig`) for improved modularity.
- **Handler Updates**:
- Refactored test cases in `workspaces_handler_test.go` to validate the new model and payload structure.
- **Repository Adjustments**:
- Updated the `CreateWorkspace` method in `workspaces.go` to reflect the new model structure.
- Ensured compatibility with nested fields during workspace creation.
- **Payload Adjustments**:
- Ensured responses match the updated API …
> fix(ws): update JSON payload for listing workspaces

- workspaces/controller/internal/controller/workspace_controller.go
This PR fixes an issue where the controller did not handle the possibility that `spec.podTemplate.podMetadata` could be empty on the WorkspaceKind, and `spec.podTemplate.podMetadata` could be empty on the Workspace.
It was simply that `labels.Merge()` is not the right way to do this, because it requires that all arguments be non-nil maps.
> fix(ws): handle empty pod metadata in controller

- workspaces/backend/api/app.go
- workspaces/backend/api/helpers.go
- workspaces/backend/api/middleware.go
- workspaces/backend/internal/server/server.go
This PR rejects clearly malformed/malicious HTTP requests by hard dropping the connection if:
1. The header size exceeds 128 Kib
2. The body size exceeds 4 Mib
Also, we were not using the `ReadJSON` method, so I have removed it to avoid confusion.
> feat(ws): introduce limits on HTTP body/header size

- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRedirectInformationView.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceRestartActionModal.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
Fixes: #146
Implemented Start, restart and stop workspace actions present in the workspace table actions kebab dropdown.
with the requested buttons and warning, from the issue description.
snapshots:
1. start with pending updates: 
2. restart without pending updates: 
3. stop without pending updates: 
4. stop with pending updates: 
5. restart with pending updates:
> feat(ws): Implement Start restart and stop workspace actions

- .github/workflows/gh-workflow-approve.yaml
- .github/workflows/ws-backend-test.yml
- .github/workflows/ws-controller-test.yaml
- .github/workflows/ws-frontend-test.yml
This PR:
1. Adds a new workflow that will trigger workflows for PRs that have the `ok-to-test` label
2. Cleans up some of the existing workflow names/permissions/formatting
3. Makes it so we run backend/controller tests if changes are made to either (as they depend on each other)
> ci: trigger workflows for PRs with `ok-to-test` label

- workspaces/frontend/package-lock.json
- workspaces/frontend/package.json
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetailsPodTemplate.tsx
As requested I added a code editor for the Pod Template section under the workspace details.
The editor will display the all yaml (mocked in the code) as read-only and will utilize the full height of its parent.
> feat(ws): Notebooks 2.0 // Frontend // Workspaces details // Pod template tab #173

- workspaces/backend/README.md
- workspaces/backend/internal/models/health_check/types.go
- workspaces/backend/internal/models/workspacekinds/types.go
- workspaces/backend/internal/models/workspaces/types.go
- workspaces/backend/internal/models/workspaces/types_create.go
To make FE/Typescript marshaling straightforward, we default our JSON format to camelCase. 
Some tests:
```json 
// http://localhost:4000/api/v1/healthcheck
{
"status": "Healthy",
"systemInfo": {
"version": "1.0.0"
}
}
````
```json  
// http://localhost:4000/api/v1/workspacekinds/jupyterlab
{
"data": {
"name": "jupyterlab",
"displayName": "JupyterLab Notebook",
"description": "A Workspace which runs JupyterLab in a Pod",
"deprecated": false,
"deprecationMessage": "This WorkspaceKind will be removed on 20XX-XX-XX, please use another WorkspaceKind.",
"hidden": false,
"icon": {
"url": "/workspaces/backend/api/v1/workspacekinds/jupyterlab/assets/icon"
},
"logo": {
"url": "/workspaces/backend/api/v1/workspacekinds/jupyterlab/assets/logo"
},
"podTemplate": {
"podMetadata": {
"labels": { …
```
> feat(ws): update JSON field names to camelCase in types and README.

- workspaces/backend/internal/models/workspaces/funcs.go
- workspaces/backend/internal/models/workspaces/types.go
This PR is for adding missing ports field to workspace model.
> feat(ws): add http service paths to WS get on backend

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_feature_request.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/gh-workflow-approve.yaml
- .github/workflows/stale.yaml
- CONTRIBUTING.md
- README.md
closes https://github.com/kubeflow/notebooks/pull/4
This PR does the following:
1. Adds github issue templates for bug reports/feature requests
2. Adds a notice to the readme in `main` about notebooks 2.0
3. Adds the "approve GHA workflows" workflow for PRs with the `ok-to-test` label
4. Adds a "stale Issue/PR workflow" (note, this will cause all the old issues to be marked as stale, but we can then go through them and mark the important ones as frozen).
5. Adds a `CONTRIBUTING.md` guide with basic info about commit signing
> chore: issue templates + readme updates + common gha

- workspaces/backend/internal/models/workspaces/funcs.go
- workspaces/backend/internal/models/workspaces/types.go
This PR is for adding missing field PendingRestart to workspace model for frontend use.
> feat(ws): add `pendingRestart` field to workspace model

- workspaces/controller/cmd/main.go
- workspaces/controller/internal/controller/suite_test.go
- workspaces/controller/internal/controller/workspace_controller.go
- workspaces/controller/internal/controller/workspacekind_controller.go
- workspaces/controller/internal/controller/workspacekind_controller_test.go
- workspaces/controller/internal/helper/build_rate_limiter.go
- workspaces/controller/internal/helper/reconcile.go
closes: https://github.com/kubeflow/notebooks/issues/245
based on: https://github.com/external-secrets/external-secrets/pull/4339
This PR is based on the implementation found in [external-secrets#4339](https://github.com/external-secrets/external-secrets/pull/4339).
The `BuildRateLimiter()` function has been implemented and added under the `controller/helper` directory.
The controller was deployed using the image from this PR. I also spun up a JupyterLab with `kubectl apply -k config/samples/`, and the logs look good.
```
kubectl logs pod/workspace-controller-controller-manager-6df69d664c-pg4kj 
2025-04-10T08:35:01Z    INFO    controller-runtime.builder      skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called     {"GVK": …
```
> feat(ws): retry failed reconciles much less aggressively

- workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx
Closes #242 
Applied Patternfly `Stack` component to ensure correct padding and spacing between the "Create workspace" title and the Patternfly progress stepper component. 
Before:
After:
> refactor(ws): Enhance "Create Workspace" Title Spacing

- workspaces/frontend/src/app/pages/Workspaces/WorkspaceConnectAction.tsx
> feat(ws): workspaces connect button sizing

- workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesSecrets.tsx
- workspaces/frontend/src/app/pages/Workspaces/Creation/properties/WorkspaceCreationPropertiesSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/shared/types.ts
closes: #267
related: depends on #262
Note: 
- The modal to create a new secret currently takes in octal value as `defaultMode` and stores it as decimal before submitting back to API
- The default mode also includes input validation to ensure the input is a valid unix permission value
[2025_05_01-15_35_11.webm](https://github.com/user-attachments/assets/36d54763-69b2-4b99-9216-80e683d1b6ae)
> feat(ws): Notebooks v2 add secrets to workspace creation properties

- workspaces/frontend/src/shared/style/MUI-theme.scss
> fix(ws): filter chip label spacings

- workspaces/backend/api/workspaces_handler_test.go
- workspaces/backend/internal/models/workspaces/types.go
- workspaces/backend/internal/models/workspaces/types_create.go
- workspaces/backend/internal/repositories/workspaces/repo.go
- workspaces/backend/openapi/docs.go
- workspaces/backend/openapi/swagger.json
- workspaces/backend/openapi/swagger.yaml
related: #239
This commit brings partial support for secrets to the backend API.  It enables the `frontend` component to successfully create a Workspace through the "wizard flow".
**HOWEVER**, it is important to note this secrets attribute is not supported within the `controller` component yet - as #240 is not yet merged. To unblock the `frontend` - the logic contained in this commit simply adds the necessary scaffolding to accept the `secrets` attribute defined within `volumes`.  Once umarshalled, the backend essentially ignores this data.  Code to fully enable the end to end flow is included in this PR - but simply commented out with `TODO:` comments denoting what can be uncommented once #240 is merged into `notebooks-v2`.  A test is also presently disabled with `XIt` - and can also be …
> fix(ws): add secrets field to backend API schema

- workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/filterWorkspacesTest.cy.ts
- workspaces/frontend/src/app/components/FormFieldset.tsx
- workspaces/frontend/src/app/components/ThemeAwareSearchInput.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/shared/components/Filter.tsx
- workspaces/frontend/src/shared/style/MUI-theme.scss
Closes #263 and #312.
Introduced FormFieldset and ThemeAwareSearchInput components to encapsulate conditional MUI theme logic for these components.
Refactored existing components to use these new theme-aware wrappers. 
Before:
After:
> feat(ws): Apply theme dependent components

- workspaces/frontend/src/app/context/useNotebookAPIState.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/ActionButton.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStartActionModal.tsx
- workspaces/frontend/src/app/pages/Workspaces/workspaceActions/WorkspaceStopActionModal.tsx
- workspaces/frontend/src/shared/api/backendApiTypes.ts
- workspaces/frontend/src/shared/api/callTypes.ts
- workspaces/frontend/src/shared/api/notebookApi.ts
- workspaces/frontend/src/shared/api/notebookService.ts
- workspaces/frontend/src/shared/mock/mockNotebookService.ts
Closes https://github.com/kubeflow/notebooks/issues/339
Start and Stop buttons are now calling their respective backend endpoints.
> feat(ws): prepare frontend calls to pause and start endpoints

- workspaces/frontend/src/app/App.tsx
- workspaces/frontend/src/app/context/BrowserStorageContext.tsx
- workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
- workspaces/frontend/src/shared/components/NamespaceSelector.tsx
closes: #[318](https://github.com/kubeflow/notebooks/issues/318)
Previous behaviors: Always use the first namespace from fetch as selected namespace
Features: 
1. Persist selected namespace across refreshes. If no such namespace exists, select the one at index 0 of the `namespaces` array
2. If namespace is changed on one tab, that change will reflect on other tabs. That will ensure consistency and won't confuse users on what the "last" selected namespace was.
> feat(ws): Persist last used namespace across refreshes and tabs

- workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSelection.tsx
- workspaces/frontend/src/shared/style/MUI-theme.scss
Closes #371 
Changes:
- Relocated description text for progress steps to display as a subtitle. 
- Updated the ProgressStepper theming to align with UX recommendations and MUI theme color palette. 
Before:
After:
> fix(ws): Update Progress Stepper with UX feedback

- workspaces/frontend/src/app/actions/WorkspaceKindsActions.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindList.tsx
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
Closes #376 and #377 
Before:
After:
> fix(ws): Action Button Alignment and Jupyter Image Display

- workspaces/frontend/src/app/AppRoutes.tsx
- workspaces/frontend/src/app/NavSidebar.tsx
- workspaces/frontend/src/shared/style/MUI-theme.scss
> fix(ws): Expose active nav item on initial Workspaces page load

- workspaces/controller/internal/webhook/suite_test.go
- workspaces/controller/internal/webhook/workspace_webhook.go
- workspaces/controller/internal/webhook/workspace_webhook_test.go
- workspaces/controller/internal/webhook/workspacekind_webhook.go
- workspaces/controller/internal/webhook/workspacekind_webhook_test.go
This PR updates the controller's validating webhook to validate the following fields:
- Workspace:
- `spec.podTemplate.podMetadata.labels`
- `spec.podTemplate.podMetadata.annotations`
- WorkspaceKind:
- `spec.podTemplate.podMetadata.labels`
- `spec.podTemplate.podMetadata.annotations`
We do this by calling the upstream [`apimachinery`](https://pkg.go.dev/k8s.io/apimachinery) implementation so we validate exactly the same as upstream:
- Labels: [`v1validation.ValidateLabels()`](https://github.com/kubernetes/apimachinery/blob/v0.33.2/pkg/apis/meta/v1/validation/validation.go#L62-L72)
- Annotations: [`apivalidation.ValidateAnnotations()`](https://github.com/kubernetes/apimachinery/blob/v0.33.2/pkg/api/validation/objectmeta.go#L44-L56)
This is important because it's quite complex to correctly …
> feat(ws): validate podMetadata for ws and wsk in webhook

- .github/workflows/OWNERS
- workspaces/backend/OWNERS
- workspaces/controller/OWNERS
- workspaces/frontend/OWNERS
This PR makes it so that our up-and-coming approvers (@andyatmiami - controller, backend /// @paulovmr - frontend) are automatically assigned as a reviewer in their respective areas.
This is in line with the [code review process](https://www.kubeflow.org/docs/about/contributing/#the-code-review-process) that should enable people to get to approver once they consistently lgtm PRs in a state which the approvers would have merged.
Additionally, it seems like we can set `labels` in the `OWNERS` files which should automatically apply those labels to PRs which change code under those paths. Hopefully this works, but we will see after we merge.
> chore: add OWNERS files with reviewers and labels

- workspaces/.dockerignore
- workspaces/backend/Dockerfile
- workspaces/backend/Makefile
closes: #323 
In this pr I fixed the make docker-build + make docker-buildx.
NOTE: When you run "make docker-buildx" you will get this ERROR:
"ERROR: failed to solve: failed to push nbv2-backend:latest: push access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: [Makefile:135: docker-buildx] Error 1 (ignored)",
Because we didn't specify the right registry in the Makefile.
> fix(ws): backend dockerfile

- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindForm.tsx
- workspaces/frontend/src/shared/api/apiUtils.ts
- workspaces/frontend/src/shared/api/backendApiTypes.ts
- workspaces/frontend/src/shared/api/notebookApi.ts
- workspaces/frontend/src/shared/api/notebookService.ts
closes: #349
related: #365
Per the community meeting on June 26th 2025, the team has come to an agreement that the creation flow should allow only a single YAML upload. Configuring pod config, properties and images will only be available when the user wishes to Edit a Workspace Kind
> feat: refactor Form View to Edit only

- workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
Closes #373 
This PR enhances the workspace creation wizard by providing more context for each step in the form flow.
Includes updated step descriptions for:
- **Kind Selection**
- **Image Selection**
- **Pod Config Selection** 
This enhancement improves the workspace creation process by helping users understand what to select and why each step matters for their workspace setup.
> fix(ws): Improve Workspace Creation Wizard Step Descriptions

- workspaces/backend/api/app.go
- workspaces/backend/api/helpers.go
- workspaces/backend/api/response_errors.go
- workspaces/backend/api/suite_test.go
- workspaces/backend/api/workspacekinds_handler.go
- workspaces/backend/api/workspacekinds_handler_test.go
- workspaces/backend/api/workspaces_handler.go
- workspaces/backend/api/workspaces_handler_test.go
- workspaces/backend/internal/repositories/workspacekinds/repo.go
- workspaces/backend/openapi/docs.go
- workspaces/backend/openapi/swagger.json
This PR adds the POST /api/v1/workspacekinds endpoint for creating a WorkspaceKind from a raw YAML upload.
The implementation adds a Create() method to the repository and the CreateWorkspaceKindHandler to process the request. The corresponding integration tests verify the success path using a static file payload and also cover key failure cases.
closes: #278
> feat(ws): backend api to create wsk with YAML

- workspaces/frontend/src/app/NavSidebar.tsx
- workspaces/frontend/src/app/components/ValidationErrorAlert.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindForm.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/fileUpload/WorkspaceKindFileUpload.tsx
- workspaces/frontend/src/shared/api/__tests__/errorUtils.spec.ts
- workspaces/frontend/src/shared/api/__tests__/notebookService.spec.ts
- workspaces/frontend/src/shared/api/apiUtils.ts
- workspaces/frontend/src/shared/api/backendApiTypes.ts
- workspaces/frontend/src/shared/api/errorUtils.ts
- workspaces/frontend/src/shared/api/notebookService.ts
- workspaces/frontend/src/shared/api/types.ts
- workspaces/frontend/src/shared/mock/mockNotebookService.ts
- workspaces/frontend/src/shared/mock/mockUtils.ts
- workspaces/frontend/src/shared/style/MUI-theme.scss
closes https://github.com/kubeflow/notebooks/issues/454
Also in this PR:
- Subpaths also activate their parent item in the nav bar
- Use builtin `<FileUpload>.dropzoneProps` to block invalid file extensions in `WorkspaceKindForm` upload
- Wrap requests to extract ErrorEnvelopes
- Make `<Alert>` title bold again
Demo:
- Trying to drop an unsupported file
- Trying to drop an unexpected WorkspaceKind format
- Trying to drop an invalid WorkspaceKind to simulate validation errors (calls create endpoint and shows the errors)
- Dropping a valid file and successfully call create endpoint
https://github.com/user-attachments/assets/12ac1720-9944-44bf-8a85-81e06d91aa42
> feat(ws): prepare frontend for validation errors during WorkspaceKind creation

- workspaces/frontend/.eslintrc.js
- workspaces/frontend/config/cspell-ignore-words.txt
- workspaces/frontend/config/cspell.config.cjs
- workspaces/frontend/config/cspell.json
- workspaces/frontend/package-lock.json
- workspaces/frontend/package.json
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/EditableLabels.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/podConfig/WorkspaceKindFormResource.tsx
- workspaces/frontend/src/app/pages/notFound/NotFound.tsx
- workspaces/frontend/src/shared/components/DeleteModal.tsx
- workspaces/frontend/src/shared/mock/mockBuilder.ts
- workspaces/frontend/src/shared/style/MUI-theme.scss
- workspaces/frontend/src/shared/utilities/useFetchState.ts
By adding this new lint rule, the `npm run test` command will fail when there are spelling errors in the source code (e.g. `error  Unknown word: "didn"  @cspell/spellchecker`)
This can be bypassed by adding the word to the `workspaces/frontend/config/cspell-ignore-words.txt` file.
> chore(ws): added cspell to enforce spelling check

- workspaces/frontend/package-lock.json
- workspaces/frontend/package.json
Fixed warning given by `npm ci`:
```
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
```
> chore(ws): upgrade deprecated rimraf transitive dependency

- workspaces/frontend/package-lock.json
- workspaces/frontend/package.json
- workspaces/frontend/src/app/App.tsx
Adds support for PatternFly [utility classes]( https://www.patternfly.org/utility-classes/about-utility-classes/).
- Added `@patternfly/patternfly/patternfly-addons.css` import to `App.tsx`
- Enables usage of PatternFly utility classes throughout the application (spacing, display, text, sizing, flex, background, etc.)
- Provides access to PatternFly's comprehensive utility class system
- Prevents inline/custom CSS for common styling patterns
1. Add `className="pf-v6-u-text-color-brand"` to the Title component on line 54 of `workspaces/frontend/src/app/App.tsx`:
```tsx
<Title headingLevel="h2" size="3xl" className="pf-v6-u-text-color-brand">
Kubeflow Notebooks 2.0
</Title>
```
2. Save the file and verify the application title text appears in blue (PatternFly brand color)
3. Remove the test …
> chore(ws): Add support for PF utility classes

- workspaces/frontend/src/app/components/ValidationErrorAlert.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/EditableLabels.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindForm.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindFormPaginatedTable.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/helpers.ts
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/image/WorkspaceKindFormImage.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/image/WorkspaceKindFormImageModal.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/podConfig/ResourceInputWrapper.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/podConfig/WorkspaceKindFormPodConfig.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/podConfig/WorkspaceKindFormResource.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/podTemplate/WorkspaceKindFormPodTemplate.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesSecrets.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/properties/WorkspaceFormPropertiesVolumes.tsx
- workspaces/frontend/src/app/types.ts
- workspaces/frontend/src/shared/api/apiUtils.ts
- workspaces/frontend/src/shared/style/MUI-theme.scss
- workspaces/frontend/src/shared/utilities/valueUnits.ts
closes: #354 
depends on: #425 
1. Add 'Edit' action to WorkspaceKind table and populate form with WS kind's data from api
2. Add advanced settings for pods in Workspace Kind Edit:
- Pod Metadata: Allow users to add labels (used for identifying, selecting, and grouping resources) and annotations (for arbitrary, non-identifying metadata)
- Culling: Add `'time'` type to `ResourceInputWrapper` and allow admin to cull inactive pods 
- Extra volume mounts
3. Enable `WorkspaceKindForm` to detect 409 errors from API
> feat(ws): Add advanced pod configurations in Workspace Edit

- workspaces/frontend/src/app/pages/WorkspaceKinds/Form/WorkspaceKindForm.tsx
- workspaces/frontend/src/shared/api/apiUtils.ts
- workspaces/frontend/src/shared/api/notebookService.ts
- workspaces/frontend/src/shared/api/types.ts
closes: #477 
DESCRIPTION: 
- Remove restYAML utility function and use restFILE with directYAML flag when handling WorkspaceKind "POST" call
- Update header `Content-Type` to `application/yaml`
> feat(ws): Refactor restYAML to restFILE

- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsImages.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsNamespaces.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsPodConfigs.tsx
- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsTable.tsx
**Description**
The current implementation of Workspace Kinds details is a list of items with plain texts, which should be reorganized. 
In this PR, we aim to improve the UX by:
- Make the Details drawer resizable so that users can easily 
- Set the minimum with of the drawer panel to 40% of the entire drawer so that all the tabs are visible on most screens
- Refactor Images, Pod Configs and Namespaces to a table view for better viewing
closes: #479 
Before
After
<video src="https://github.com/user-attachments/assets/3a1d2eff-9e11-4000-a2b3-d30bee197c72" />
> feat(ws): Make Workspace Kind drawer resizable and add table view to WS kind details

- workspaces/frontend/src/app/pages/Workspaces/Form/WorkspaceForm.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/kind/WorkspaceFormKindSelection.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigDetails.tsx
- workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
Closes #374 
The workspace creation wizard had inconsistent scrolling behavior and lacked proper drawer component nesting, preventing users from scrolling through workspace options while also viewing information in the drawer panel. Dual scrolling is now supported. 
Refactored the workspace form to use PatternFly `Drawer` component with proper nesting structure to support dual scrolling throughout the workspace kind creation wizard.
- **Restructured drawer component hierarchy** - moved drawer to parent level with centralized state management
- **Fixed component nesting** - properly nested `DrawerContent`, `DrawerContentBody`, and `DrawerPanelContent` for consistent scrolling
- **Simplified selection components** - removed individual drawer wrappers and consolidated drawer logic
Before: …
> fix(ws): Implement dual scrolling for workspace kind wizard

- workspaces/backend/api/suite_test.go
- workspaces/backend/internal/models/workspacekinds/funcs.go
- workspaces/backend/internal/models/workspacekinds/types.go
- workspaces/backend/openapi/docs.go
- workspaces/backend/openapi/swagger.json
> feat(ws): add ws counts to backend wsk model

- workspaces/frontend/.dockerignore
- workspaces/frontend/Dockerfile
- workspaces/frontend/nginx.conf
closes #392 
I've created a Dockerfile for the frontend component, which allows for containerization of the frontend application. Currently, the frontend can only be run locally via the command line. 
now we can run the frontend as a k8s workload resource, and its separate from the backend container.
Build the frontend image:
`docker build -f Dockerfile -t frontend-img .`
Run the container and expose it on port 8080:
`docker run -it --rm --name workspace-frontend -p 8080:8080  frontend-img`
> feat(ws): containerize frontend component

- workspaces/backend/README.md
- workspaces/backend/api/app.go
- workspaces/backend/api/workspace_actions_handler.go
- workspaces/backend/api/workspace_actions_handler_test.go
- workspaces/backend/internal/models/workspaces/actions/funcs.go
- workspaces/backend/internal/models/workspaces/actions/types.go
- workspaces/backend/internal/repositories/workspaces/repo.go
- workspaces/backend/openapi/docs.go
- workspaces/backend/openapi/swagger.json
related: https://github.com/kubeflow/notebooks/issues/298
- Added PauseActionWorkspaceHandler to handle pausing or unpausing a given workspace
- Introduced single new route for starting and pausing workspaces in the API.
- `api/v1/workspaces/{namespace}/{name}/actions/pause`
- pausing or unpausing operation is specified in the request payload
- Created a new WorkspaceActionPauseEnvelope type for successful responses.
- Leveraging JSONPatch / client.RawPatch to ensure Workspace in "valid state" before attempting action
- for `start`: `spec.paused` must be `true`, and `status.state` must be `Paused`
- for `pause`: `spec.paused` must be `false`
- note: I would love to have a `status.state` check here of `status.state != Paused`, but that type of comparison is not supported in …
> feat(ws): add workspace pause actions backend API

- .github/workflows/validate-planning-label.yml
related: https://github.com/kubeflow/notebooks/issues/327
This new GitHub Actions workflow listens for the 'opened' and 'labeled' events on GitHub issues and ensures any issue opened (or labelled) with a `kind/plan-xxx` label meets the following criteria:
- only users listed in the `AUTHORIZED_USER` JSON array can label an issue with the `kind/plan-xxx` label
- at most one of the `kind/plan-xxx` labels can exist on a given issue
The set of supported/expected `kind/plan-xxx` labels are:
- `kind/plan-epic`
- `kind/plan-feature`
- `kind/plan-task`
If an issue (with a `kind/plan-xxx` label) is **opened** by a non-authorized user - the issue will be automatically closed when the GitHub action fires.
If an issue is labelled with the `kind/plan-xxx` label by an unauthorized user - the …
> chore: enforce planning label rules for issues

- .github/workflows/slash-commands.yaml
related: #325
This new GitHub Actions workflow listens for issue comments and processes commands to add or remove sub-issues using the Javascript client. It includes error handling and posts feedback to the issue for auditability as well as if any errors occur during execution.
Acceptable input formats (and multiple space-delimited arguments can be provided):
```
/add-sub-issue #1
/add-sub-issue 1
/add-sub-issue https://github.com/kubeflow/notebooks/issues/1
```
Additionally, the entirety of a comment is scanned/parsed by the GHA - so the following is also valid:
```
we need these!
/add-sub-issue #1 #2
and we don't need these
/remove-sub-issue #3 #4
```
- this would add issues 1 and 2 and remove issues 3 and 4 from the "parent" issue on which the comment was added.
:information_source: Be …
> chore: create `/add-sub-issue` and `/remove-sub-issue` commands

- workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
- workspaces/frontend/src/app/hooks/__tests__/useWorkspaceCountPerKind.spec.tsx
- workspaces/frontend/src/app/hooks/useWorkspaceCountPerKind.ts
- workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsTable.tsx
- workspaces/frontend/src/shared/api/backendApiTypes.ts
- workspaces/frontend/src/shared/mock/mockBuilder.ts
- workspaces/frontend/src/shared/mock/mockNotebookServiceData.ts
closes: https://github.com/kubeflow/notebooks/issues/418
This pull request introduces enhancements to the workspace management system, focusing on improving the handling of workspace counts, adding support for cluster metrics, and improving test coverage. The key changes include updating the `useWorkspaceCountPerKind` hook to use the data provided by the backend instead of manually calculating them, adding cluster metrics to workspace-related types, and introducing tests for workspace count calculations.
* Updated the `NamespaceContextProvider` to ensure the last used namespace is valid and falls back to the first available namespace if necessary.
* Fixed a potential issue in `WorkspaceKindDetailsTable` where `rowPages[page - 1]` could be undefined, preventing runtime errors. The empty …
> feat(ws): use workspace counts from API response

- workspaces/frontend/src/app/pages/Workspaces/Details/WorkspaceDetails.tsx
Logs and Pod Template tabs now are not rendered while they are not fully implemented:
> chore(ws): comment workspace details logs and pod template tabs while they are not supported

- workspaces/frontend/config/webpack.prod.js
- workspaces/frontend/package.json
- workspaces/frontend/src/app/App.tsx
- workspaces/frontend/src/shared/style/MUI-theme.scss
closes: #510
Description: Introduce Production Mode in Webpack and Conditionally hide UI's masthead when the application is deployed inside another application
> feat: Conditionally render masthead on Production and Standalone modes

- workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspace.mock.ts
- workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/WorkspaceDetailsActivity.cy.ts
- workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/filterWorkspacesTest.cy.ts
- workspaces/frontend/src/app/context/NamespaceContextProvider.tsx
- workspaces/frontend/src/app/hooks/__tests__/useWorkspaces.spec.tsx
- workspaces/frontend/src/app/hooks/useWorkspaces.ts
- workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx
closes: #583
Currently, the UI sends a faulty API call to `/api/v1/workspaces`, indicating no namespace is selected, resulting in a `404` error. Instead, render loading spinner when namespace is being fetched while loading Workspaces.
> feat: Render Loading if Namespaces are fetching

- workspaces/backend/Makefile
- workspaces/controller/Makefile
- workspaces/frontend/Makefile
ℹ️  _NO GH ISSUE_
After discussion with the Kubeflow WG lead - concerns were raised about including `linux/s390x` support in our multi-arch builds for the following reasons:
- not clear we could in good faith support this system due to lack of hardware / potential emulation issues
- not clear there is enough of a need from community to support `linux/s390x` for Kubeflow Notebooks.
As a result - we are going to remove the `linux/s390x` target from our multi-arch builds logic for all the `workspaces` components.
Additionally, included a minor fix to explicitly specify the `v8` variant of `linux/arm64`.  Today `linux/arm64` and `linux/arm64/v8` are essentially the same - but that could change if there was ever a `v9` variant introduced.  As such - opting to be explicit here.
> chore: update supported platforms for multi-arch builds
