kubeflow/notebooks

workspaces/frontend/jest.config.js, workspaces/frontend/package-lock.json, workspaces/frontend/package.json, workspaces/frontend/src/__mocks__/mockNamespaces.ts, workspaces/frontend/src/__mocks__/styleMock.js, workspaces/frontend/src/__mocks__/utils.ts, workspaces/frontend/src/__tests__/unit/jest.d.ts, workspaces/frontend/src/__tests__/unit/jest.setup.ts, workspaces/frontend/src/__tests__/unit/testUtils/hooks.spec.ts, workspaces/frontend/src/__tests__/unit/testUtils/hooks.ts, workspaces/frontend/src/app/App.tsx, workspaces/frontend/src/app/const.ts, workspaces/frontend/src/app/context/NotebookContext.tsx, workspaces/frontend/src/app/context/useNotebookAPIState.tsx, workspaces/frontend/src/app/hooks/useNamespaces.ts, workspaces/frontend/src/app/hooks/useNotebookAPI.ts, workspaces/frontend/src/app/types.ts, workspaces/frontend/src/shared/api/__tests__/errorUtils.spec.ts, workspaces/frontend/src/shared/api/__tests__/notebookService.spec.ts, workspaces/frontend/src/shared/api/apiUtils.ts, workspaces/frontend/src/shared/api/errorUtils.ts, workspaces/frontend/src/shared/api/notebookService.ts, workspaces/frontend/src/shared/api/types.ts, workspaces/frontend/src/shared/api/useAPIState.ts, workspaces/frontend/src/shared/typeHelpers.ts, workspaces/frontend/src/shared/utilities/const.ts, workspaces/frontend/src/shared/utilities/useFetchState.ts, workspaces/frontend/tsconfig.json
=> feat(ws): Fetch API Infra

workspaces/frontend/src/app/AppRoutes.tsx, workspaces/frontend/src/app/pages/Debug/Debug.tsx
Fix https://github.com/kubeflow/notebooks/issues/182
=> feat(ws): Notebooks 2.0 // Frontend // Rename settings to debug

workspaces/frontend/package-lock.json
=> chore(ws): Upgrade vulnerable packages

workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationPodConfigSelection.tsx
=> feat(ws): add initial workspace creation pod config step frontend

workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx, workspaces/frontend/src/shared/style/MUI-theme.scss
=> feat(ws): Add MUI Theming Support for Workspace Creation

workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageDetails.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageFilter.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationImageSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationKindList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreationKindSelection.tsx, workspaces/frontend/src/shared/types.ts
closes: https://github.com/kubeflow/notebooks/issues/223
=> feat(ws): add workspace creation image step frontend

workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageDetails.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigDetails.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigSelection.tsx, workspaces/frontend/src/shared/types.ts
closes: https://github.com/kubeflow/notebooks/issues/234
=> feat(ws): add workspace creation pod config step frontend

workspaces/frontend/config/webpack.common.js, workspaces/frontend/package-lock.json, workspaces/frontend/package.json, workspaces/frontend/src/app/context/NotebookContext.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/WorkspaceCreation.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/image/WorkspaceCreationImageSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/kind/WorkspaceCreationKindSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/labelFilter/FilterByLabels.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigList.tsx, workspaces/frontend/src/app/pages/Workspaces/Creation/podConfig/WorkspaceCreationPodConfigSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/ExpandedWorkspaceRow.tsx, workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx, workspaces/frontend/src/shared/types.ts
=> chore(ws): add fork-ts-checker-webpack-plugin and fix typescript errors

workspaces/frontend/package-lock.json, workspaces/frontend/package.json
Upgrades PatternFly to the latest version (6.2.0) for new components, design improvements, accessibility enhancements, bug fixes, and performance optimizations. This keeps us aligned with the latest Patternfly design system standards and reduces tech debt.
Closes: #255
=> chore(ws): Upgrade to Patternfly 6.2.0

workspaces/frontend/src/shared/style/MUI-theme.scss
Closes https://github.com/kubeflow/notebooks/issues/246
Before:
After:
=> feat(ws): Apply box-shadow to cards in workspace creation wizard

workspaces/frontend/src/app/pages/Workspaces/Workspaces.tsx, workspaces/frontend/src/shared/components/Filter.tsx
=> fix(ws): update component structure to fix create ws button rendering

workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceDetails.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceDetailsOverview.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx
closes: #252
create Workspace Kind details drawer
=> feat(ws): Workspace Kind details drawer #252

workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetails.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsPodConfigs.tsx
closes https://github.com/kubeflow/notebooks/issues/358
=> feat(ws): added pod configs tab to workspace kind details

workspaces/frontend/package-lock.json, workspaces/frontend/package.json
Package upgraded using `npm audit fix --force`.
=> chore(ws): Upgrade vulnerable package webpack-dev-server

workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx
=> feat(ws): Make Create Workspace Kind button visible

workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsImages.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsNamespaces.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/details/WorkspaceKindDetailsPodConfigs.tsx, workspaces/frontend/src/shared/style/MUI-theme.scss
Closes #459, #460
Before:
After:
=> fix(ws): normalize text case for workspace count buttons, update column header

workspaces/frontend/src/__tests__/cypress/cypress/tests/mocked/workspaces/filterWorkspacesTest.cy.ts, workspaces/frontend/src/app/components/WorkspaceTable.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/WorkspaceKinds.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/summary/WorkspaceKindSummary.tsx, workspaces/frontend/src/app/pages/WorkspaceKinds/summary/WorkspaceKindSummaryExpandableCard.tsx, workspaces/frontend/src/shared/style/MUI-theme.scss
Closes #493, #247 
This pull request refactors the `WorkspaceTable` filter logic to fix a bug with the "Clear all filters" button and align its implementation with the `WorkspaceKinds` filter logic.
**Changes in this PR**:
*   Fixed "Clear all filters" Bug
* The "Clear all filters" button was persisting in the UI due to a race condition / mismatch between our state management and PF internal logic caused by the `<Filter>` component in the `shared` folder. 
* `WorkspaceTable` now directly applies a `Toolbar` implementation like in `WorkspaceKinds.tsx`.
*  Applied Empty State
* Now showing the empty state in the `WorkspaceTable` when no filter results are found.
* Matches the behavior of the `WorkspaceKinds` page.
* Removed Popper from filter implementation
* Popper is not recommended for …
=> fix(ws): Refactors toolbar and filter logic to fix "clear all filters" bug in workspace list view

workspaces/frontend/src/app/components/WorkspaceTable.tsx
closes: https://github.com/kubeflow/notebooks/issues/501
=> feat(ws): fix workspaces table pagination

workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageList.tsx, workspaces/frontend/src/app/pages/Workspaces/Form/image/WorkspaceFormImageSelection.tsx, workspaces/frontend/src/app/pages/Workspaces/Form/labelFilter/FilterByLabels.tsx, workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigList.tsx, workspaces/frontend/src/app/pages/Workspaces/Form/podConfig/WorkspaceFormPodConfigSelection.tsx
=> fix(ws): fixed filter by labels during workspace creation

.github/workflows/slash-commands.yaml, .github/workflows/validate-planning-label.yml
@liavweiss has been helping me with a lot of planning discussions and been involved with notebooks-v2 for awhile now.  it will be helpful to give him the ability to create epics/features/tasks and start to own them.
=> chore: add liavweiss as epic owner to relevant GHAs
